# Generated by Django 4.0.1 on 2022-10-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default='', max_length=40)),
                ('number', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'verbose_name': 'Часть файлов',
                'verbose_name_plural': 'Части файлов',
            },
        ),
    ]
