# Generated by Django 4.0.1 on 2022-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_filepart_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepart',
            name='size',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
