# Generated by Django 4.1.2 on 2022-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_filepart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
