# Generated by Django 4.1.2 on 2022-11-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_externallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadlLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default='', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'verbose_name': 'Ссылка загрузки',
                'verbose_name_plural': 'Ссылки загрузки',
            },
        ),
    ]
