# Generated by Django 4.1.2 on 2022-11-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0017_users1c_container_statuses_enabled'),
        ('file', '0007_uploadllink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(default='', max_length=40)),
                ('type', models.CharField(default='', max_length=40)),
                ('name', models.CharField(default='', max_length=150)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
            ],
            options={
                'verbose_name': 'Владелец файла',
                'verbose_name_plural': 'Владельцы файлов',
            },
        ),
    ]
