# Generated by Django 4.1.2 on 2022-11-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0017_users1c_container_statuses_enabled'),
        ('file', '0008_fileowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(default='', max_length=40)),
                ('number', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('file_id', models.CharField(default='', max_length=40)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
            ],
            options={
                'verbose_name': 'Версия файла',
                'verbose_name_plural': 'Версии файлов',
            },
        ),
    ]
