# Generated by Django 4.0.1 on 2022-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1c', models.CharField(max_length=40)),
                ('strnum', models.IntegerField()),
                ('product', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('quantity1', models.FloatField()),
                ('quantity2', models.FloatField()),
                ('quantity3', models.FloatField()),
                ('quantity4', models.FloatField()),
                ('quantity5', models.FloatField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
