# Generated by Django 4.1.2 on 2022-11-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users1c', '0010_users1c_recipes_enabled'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('color_number', models.CharField(default=None, max_length=15)),
                ('created', models.DateTimeField()),
                ('id1c', models.CharField(default='', max_length=40)),
                ('delivered1c', models.BooleanField(default=False)),
                ('id_deleted', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепт',
            },
        ),
    ]
