# Generated by Django 4.1.2 on 2022-11-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_warehousecells'),
        ('recipe', '0003_alter_recipe_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='end_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='end_product_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipegoods',
            name='characteristic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.characteristics'),
        ),
    ]
