# Generated by Django 4.1.2 on 2022-11-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_end_product_recipe_end_product_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
