# Generated by Django 4.1.2 on 2022-11-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_warehousecells'),
        ('users1c', '0013_users1c_outcome_enabled'),
        ('contractors', '0001_initial'),
        ('recipe', '0005_recipe_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('end_product_text', models.TextField(blank=True, default=None, null=True)),
                ('color_number', models.CharField(default=None, max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id1c', models.CharField(default='', max_length=40)),
                ('delivered1c', models.BooleanField(default=False)),
                ('id_deleted', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractors')),
                ('end_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
            ],
            options={
                'verbose_name': 'Заявка на рецепт',
                'verbose_name_plural': 'Заявка на рецепт',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipeorder'),
        ),
    ]
