# Generated by Django 4.0.1 on 2022-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHeaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestheaders',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
