# Generated by Django 4.0.1 on 2022-01-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHeaders', '0002_alter_requestheaders_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestheaders',
            old_name='header',
            new_name='http_user_agent',
        ),
    ]
