# Generated by Django 4.1.2 on 2022-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id1c', models.CharField(blank=True, default='', max_length=40)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Ключ доступа',
                'verbose_name_plural': 'Ключи доступа',
            },
        ),
    ]
