# Generated by Django 4.0.1 on 2022-01-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='error_text',
            field=models.TextField(max_length=1000),
        ),
    ]
