# Generated by Django 4.0.1 on 2022-08-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users1c', '0008_users1c_invent_enabled'),
        ('products', '0008_warehouses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id1c', models.CharField(default='', max_length=40)),
                ('delivered_1c', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.characteristics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.warehouses')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
    ]
