# Generated by Django 4.0.1 on 2022-08-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_warehousecells'),
        ('invent', '0002_alter_invent_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='invent',
            name='warehouse_cell',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousecells'),
        ),
    ]
