# Generated by Django 4.0.1 on 2022-10-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_warehousecells'),
        ('invent', '0003_invent_warehouse_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invent',
            name='characteristic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.characteristics'),
        ),
        migrations.AlterField(
            model_name='invent',
            name='warehouse_cell',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousecells'),
        ),
    ]
