# Generated by Django 4.0 on 2022-01-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users1c', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1c',
            new_name='Users1c',
        ),
    ]
