# Generated by Django 4.0 on 2022-01-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0002_rename_user1c_users1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users1c',
            name='user',
        ),
    ]
