# Generated by Django 4.0.1 on 2022-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0004_users1c_idbitrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='webhook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users1c',
            name='id1c',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
