# Generated by Django 4.0.1 on 2022-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0005_users1c_webhook_alter_users1c_id1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='dmbase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users1c',
            name='dmuser',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
