# Generated by Django 4.0.1 on 2022-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0006_users1c_dmbase_users1c_dmuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='dmbase2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='users1c',
            name='dmuser2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
