# Generated by Django 4.0.1 on 2022-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0007_users1c_dmbase2_users1c_dmuser2'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='invent_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
