# Generated by Django 4.0.1 on 2022-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0008_users1c_invent_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='files_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
