# Generated by Django 4.1.2 on 2022-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0009_users1c_files_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='recipes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
