# Generated by Django 4.1.2 on 2022-11-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_warehousecells'),
        ('users1c', '0010_users1c_recipes_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='acceptcash_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users1c',
            name='bitrix_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users1c',
            name='orders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users1c',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouses'),
        ),
    ]
