# Generated by Django 4.1.2 on 2022-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0011_users1c_acceptcash_enabled_users1c_bitrix_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='leftovers_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
