# Generated by Django 4.1.2 on 2022-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0012_users1c_leftovers_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='outcome_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
