# Generated by Django 4.1.2 on 2022-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0013_users1c_outcome_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='recepi_erders_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
