# Generated by Django 4.1.2 on 2022-11-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0014_users1c_recepi_erders_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users1c',
            old_name='recepi_erders_enabled',
            new_name='recepi_orders_enabled',
        ),
    ]
