# Generated by Django 4.1.2 on 2022-11-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0015_rename_recepi_erders_enabled_users1c_recepi_orders_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users1c',
            old_name='recepi_orders_enabled',
            new_name='recipe_orders_enabled',
        ),
    ]
