# Generated by Django 4.1.2 on 2022-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0016_rename_recepi_orders_enabled_users1c_recipe_orders_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='container_statuses_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
