# Generated by Django 4.1.2 on 2022-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0018_users1c_telegram_id_containerfilesinfobotuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users1c',
            name='container_statuses_edit_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
