# Generated by Django 4.0.1 on 2022-01-09 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users1c', '0003_remove_users1c_user'),
        ('currency', '0001_initial'),
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('order_number', models.CharField(default=None, max_length=15)),
                ('order_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id1c', models.CharField(default='', max_length=40)),
                ('delivered1c', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractors')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c')),
            ],
            options={
                'verbose_name': 'Получение денег',
                'verbose_name_plural': 'Получение денег',
            },
        ),
    ]
