# Generated by Django 4.0.1 on 2022-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accept_cash', '0002_alter_acceptcash_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptcash',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
