# Generated by Django 4.1.2 on 2022-11-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users1c', '0009_users1c_files_enabled'),
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users1c.users1c'),
            preserve_default=False,
        ),
    ]
