# Generated by Django 4.0.1 on 2022-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=255)),
                ('idbitrix', models.IntegerField(default=0)),
                ('data', models.TextField(max_length=10000)),
            ],
        ),
    ]
