# Generated by Django 4.0.1 on 2022-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixqueue',
            name='exexuted',
            field=models.BooleanField(default=False),
        ),
    ]
