# Generated by Django 4.0.1 on 2022-04-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrixqueue', '0002_bitrixqueue_exexuted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitrixqueue',
            old_name='exexuted',
            new_name='executed',
        ),
    ]
