# Generated by Django 4.0 on 2022-01-04 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id1c',
            field=models.CharField(default=uuid.UUID('bd50e1fc-6d80-11ec-943e-7085c264e843'), max_length=40),
        ),
    ]
