# Generated by Django 4.0 on 2022-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered1c',
            field=models.BooleanField(default=False),
        ),
    ]
