# Generated by Django 4.0 on 2022-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=10)),
                ('id1c', models.CharField(max_length=40)),
            ],
        ),
    ]
