# Generated by Django 4.1.2 on 2022-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockschema',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
