# Generated by Django 4.0 on 2022-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('fullname', models.TextField(max_length=1000)),
                ('sfullname', models.TextField(max_length=1000)),
                ('id1c', models.CharField(max_length=40)),
            ],
        ),
    ]
