# Generated by Django 4.0.1 on 2022-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_is_active_products_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='fullname',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sfullname',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
