# Generated by Django 4.0.1 on 2022-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_article_alter_products_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='products',
            name='fullname',
            field=models.TextField(blank=True, default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='sfullname',
            field=models.TextField(blank=True, default=None, max_length=1000),
        ),
    ]
