# Generated by Django 4.0.1 on 2022-08-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_warehouses_sname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouses',
            name='sname',
        ),
    ]
