# Generated by Django 4.0.1 on 2022-08-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_warehouses_sname'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('sname', models.CharField(blank=True, default=None, max_length=255)),
                ('section', models.CharField(blank=True, default=None, max_length=3)),
                ('line', models.CharField(blank=True, default=None, max_length=3)),
                ('rack', models.CharField(blank=True, default=None, max_length=5)),
                ('stage', models.CharField(blank=True, default=None, max_length=3)),
                ('position', models.CharField(blank=True, default=None, max_length=2)),
                ('is_group', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_id1c', models.CharField(max_length=40)),
                ('id1c', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Складская ячейка',
                'verbose_name_plural': 'Складские ячейки',
            },
        ),
    ]
